[project]
name = "module-1"
version = "0.1.0"
description = "Assignment for the Module 1 of the Data Engineering Zoomcamp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas",
    "click",
    "sqlalchemy",
    "tqdm",
    "pyarrow",
    "psycopg2-binary",
]
